name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:

      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      
      # Debug: List repository contents
      - name: Debug - List repository contents
        run: ls -R

      # Debug: Check Unity version
      - name: Check Unity version
        run: |
          if command -v unity-editor; then
            unity-editor -version
          elif command -v /opt/unity/Editor/Unity; then
            /opt/unity/Editor/Unity -version
          else
            echo "Unity is not installed or not found in expected locations."
          fi

      # Debug: Check if project settings exist
      - name: Check if Unity project is detected
        run: |
          if [ -f ProjectSettings/ProjectVersion.txt ]; then
            echo "Unity project detected."
            cat ProjectSettings/ProjectVersion.txt
          else
            echo "⚠️ ERROR: Project settings file not found! Make sure the Unity project path is correct."
            exit 1
          fi

      # Debug: Check environment variables
      - name: Debug - Print environment variables
        run: env

      # Build the project
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          unityVersion: 2022.3.12f1  # Update this to match your Unity version

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
