name: Build my Game

on: [push]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:

      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache Library folder to speed up builds
      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      
      # Debug: List repository contents
      - name: Debug - List repository contents
        run: ls -R

      # Debug: Check Unity version
      - name: Check Unity version
        run: |
          if command -v unity-editor; then
            unity-editor -version
          elif command -v /opt/unity/Editor/Unity; then
            /opt/unity/Editor/Unity -version
          else
            echo "Unity is not installed or not found in expected locations."
          fi

      # Debug: Check if project settings exist
      - name: Check if Unity project is detected
        run: |
          if [ -f ProjectSettings/ProjectVersion.txt ]; then
            echo "Unity project detected."
            cat ProjectSettings/ProjectVersion.txt
          else
            echo "⚠️ ERROR: Project settings file not found! Make sure the Unity project path is correct."
            exit 1
          fi

      # Debug: Check environment variables
      - name: Debug - Print environment variables
        run: env

      # Build the project
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          unityVersion: 6000.0.36f1  # Update this to match your Unity version

      # Move contents of build/WebGL to build
      - name: Move build files
        run: |
          mkdir -p build_temp
          mv build/WebGL/* build_temp/
          rm -r build
          mv build_temp build
          
      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build/WebGL
          retention-days: 14

  # Deploy to Pages
  deployPages: 
    needs: build
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
       # Checkout the repository first
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Download the build artifacts
      - uses: actions/download-artifact@v4
        with:
          name: Build
          path: build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with: 
          folder: build
          branch: gh-pages
          clean: true  # This will clean up the gh-pages branch
          single-commit: true
